-- 코드를 입력하세요

# 1. 각 책별로 매출액 계산하기
# 2. 카테고리별로, 저자의 매출액 합 계산하기

WITH BOOK_TOTAL_SALES AS (
    SELECT BOOK.BOOK_ID, BOOK_SALES.SALES * BOOK.PRICE AS REVENUE, BOOK_SALES.SALES_DATE
    FROM BOOK
    JOIN BOOK_SALES
    ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
)

SELECT AUTHOR.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, SUM(BOOK_TOTAL_SALES.REVENUE) AS BOOK_TOTAL_SALES
FROM BOOK
JOIN AUTHOR
ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
JOIN BOOK_TOTAL_SALES
ON BOOK.BOOK_ID = BOOK_TOTAL_SALES.BOOK_ID
WHERE BOOK_TOTAL_SALES.SALES_DATE LIKE '2022-01-__'
GROUP BY BOOK.AUTHOR_ID, BOOK.CATEGORY
ORDER BY AUTHOR.AUTHOR_ID ASC, BOOK.CATEGORY DESC;
