-- 코드를 입력하세요

# 1. 각 책별로 매출액 계산하기
# 2. 카테고리별로, 저자의 매출액 합 계산하기

WITH BOOK_REVENUE AS (
    SELECT BOOK.BOOK_ID, BOOK_SALES.SALES * BOOK.PRICE AS REVENUE, BOOK_SALES.SALES_DATE
    FROM BOOK
    JOIN BOOK_SALES
    ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
)

SELECT AUTHOR.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, SUM(BOOK_REVENUE.REVENUE) AS BOOK_TOTAL_SALES
FROM BOOK
JOIN AUTHOR
ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
JOIN BOOK_REVENUE
ON BOOK.BOOK_ID = BOOK_REVENUE.BOOK_ID
WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY BOOK.AUTHOR_ID, BOOK.CATEGORY
ORDER BY AUTHOR.AUTHOR_ID ASC, BOOK.CATEGORY DESC;