-- 코드를 입력하세요
# 입양을 간 동물 중, 보호 기간이 가장 길었던 동물 두 마리의 아이디와 이름 조회
# 보호 기간이 긴 순으로 조회

# DURATION_INFO:
# SELECT ANIMAL_ID, ANIMAL_NAME, DATEDIFF AS DURATION
# FROM ANIMAL_INS JOIN ANIMAL_OUTS ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
# ORDER BY DURATION DESC;


WITH DURATION_INFO AS (
    SELECT
        I.ANIMAL_ID,
        I.NAME,
        DATEDIFF(O.DATETIME, I.DATETIME) + 1 AS DURATION
    FROM ANIMAL_INS I
    JOIN ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
    ORDER BY DURATION DESC
    LIMIT 2
)

SELECT ANIMAL_ID, NAME
FROM DURATION_INFO
