-- 코드를 입력하세요


# 음식종류별로 즐겨찾기 수가 가장 많은 식당의 음식 종류, ID, 식당 이름, 즐겨찾기 수를 조회
# 


SELECT REST_INFO.FOOD_TYPE, REST_INFO.REST_ID, REST_INFO.REST_NAME, REST_INFO.FAVORITES
FROM REST_INFO
JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) FOOD_TYPES
ON REST_INFO.FOOD_TYPE = FOOD_TYPES.FOOD_TYPE AND REST_INFO.FAVORITES = FOOD_TYPES.MAX_FAVORITES
ORDER BY REST_INFO.FOOD_TYPE DESC;

