-- 코드를 입력하세요

# 평균 대여 기간이 7일 이상인 자동차들의 자동차 ID와 평균 대여 기간
# ROUND(FIELD, 1)

# 1. DURATION 구하기
# 2. DURATION의 평균 구하기


WITH DURATION_INFO AS (
    SELECT HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)

SELECT CAR_ID, ROUND(AVG(DURATION), 1) AS AVERAGE_DURATION
FROM DURATION_INFO
GROUP BY CAR_ID
HAVING ROUND(AVG(DURATION), 1) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;




