-- 코드를 입력하세요
# 2021년에 가입한 전체 회원들 중 상품을 구매한 회원수와 상품을 구매한 회원의 비율(가입한 회원 중 상품 구매한
# 회원 수) / (2021년에 가입한 전체 회원 수)를 년, 월 별로 출력하는 sql문 작성하기
# 날짜 / 회원 ID / 상품 ID 조합에 대해서 하나의 판매 데이터만 존재


# 1. 2021년에 가입한 전체 회원들 구하기, 년 / 월 별로 구분
# 2. 2021년에 가입한 전체 회원들 중 상품을 구매한 회원의 비율을 년, 월별로 출력하기

WITH 2021_MONTHLY_USER_INFO AS (
    SELECT USER_ID, YEAR(JOINED) AS JOINED_YEAR, MONTH(JOINED) AS JOINED_MONTH
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
),
2021_PURCHASED_USER_INFO AS (
    SELECT DISTINCT(ONLINE_SALE.USER_ID), YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
    FROM 2021_MONTHLY_USER_INFO
    JOIN ONLINE_SALE
    ON 2021_MONTHLY_USER_INFO.USER_ID = ONLINE_SALE.USER_ID
)


SELECT YEAR, MONTH, COUNT(USER_ID) AS PURCHASED_USERS, ROUND(COUNT(USER_ID) / (
    SELECT COUNT(*)
    FROM 2021_MONTHLY_USER_INFO
), 1) AS PURCHASED_RATIO 
FROM 2021_PURCHASED_USER_INFO
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC;


# SELECT COUNT(USER_ID), JOINED_YEAR AS YEAR, JOINED_MONTH AS MONTH
# FROM 2021_MONTHLY_USER_INFO
# GROUP BY JOINED_YEAR, JOINED_MONTH


# WITH MONTHLY_USER_INFO AS (
#     SELECT YEAR(JOINED) AS JOINED_YEAR, MONTH(JOINED) AS JOINED_MONTH, USER_ID
#     FROM USER_INFO
#     WHERE YEAR(JOINED) = 2021
# ),
# MONTHLY_ONLINE_SALE AS (
#     SELECT YEAR(SALES_DATE) AS SALES_YEAR, MONTH(SALES_DATE) AS SALES_MONTH, USER_ID
#     FROM ONLINE_SALE
# ),
# ACTIVE_USER_INFO AS (
#     SELECT INFO.USER_ID
#     FROM MONTHLY_ONLINE_SALE SALE
#     WHERE EXISTS (
#         SELECT 1
#         FROM MONTHLY_USER_INFO INFO
#         WHERE SALE.USER_ID = INFO.USER_ID
#     )
# )

# SELECT * FROM ACTIVE_USER_INFO;





# 년/월
# (가입한 회원 중 상품 구매한 회원 수 / 가입한 전체 회원 수)를 년, 월별로 출력
# 상품을 구매한 회원의 비율은 소수점 두번째자리에서만 반올림
# ORDER BY YEAR ASC, MONTH ASC;

# 1. USER_INFO에서 USER_ID, 가입년, 가입일 column 가진 테이블 생성 => USER_JOINED_INFO
# 2. ONLINE_SALE에서 USER_ID, 구매년, 구매일 column 가진 테이블 생성 => PURCHASE_INFO
# 3. 상품을 구매했던 이력이 있는 유저를 필터링해야 한다.
#    => RIGHT INNER JOIN
# 4. 년/월 테이블 생성