-- 코드를 입력하세요

# 자동차 종류가 '트럭'인 자동차의 대여 기록
# 대여 기록 별로 대여 금액을 구하기
# 대여 기록 ID와 대여 금액 리스트 출력

# 1. CAR_RENTAL_COMPANY_CAR에서 트럭만 나오도록 필터링하기
# 2. TRUCK_INFO JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY ON CAR_ID로 history 중에 트럭인 것만
#    나오도록 거르기, duration 구하기
# 3. TRUCK_HISTORY_INFO JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN
#    ON PLAN.CAR_TYPE = '트럭'


WITH TRUCK_INFO AS (
    SELECT CAR_ID, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '트럭'
),
TRUCK_HISTORY_INFO AS (
    SELECT C.HISTORY_ID, T.CAR_ID, T.DAILY_FEE, DATEDIFF(C.END_DATE, C.START_DATE) + 1 AS DURATION
    FROM TRUCK_INFO T
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY C
    ON T.CAR_ID = C.CAR_ID
),
TRUCK_DISCOUNT_INFO AS (
    SELECT DURATION_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
),
TRUCK_POSSIBLE_FEES AS (
    SELECT
        H.HISTORY_ID,
        H.DURATION,
        H.DAILY_FEE,
        D.DISCOUNT_RATE,
        D.DURATION_TYPE,
        CASE
            WHEN D.DURATION_TYPE = '90일 이상' AND H.DURATION >= 90 THEN FLOOR(H.DAILY_FEE * H.DURATION * (1 - 0.01 * CAST(REPLACE(D.DISCOUNT_RATE, '%', '') AS SIGNED)))
            WHEN D.DURATION_TYPE = '30일 이상' AND H.DURATION >= 30 THEN FLOOR(H.DAILY_FEE * H.DURATION * (1 - 0.01 * CAST(REPLACE(D.DISCOUNT_RATE, '%', '') AS SIGNED)))
            WHEN D.DURATION_TYPE = '7일 이상' AND H.DURATION >= 7 THEN FLOOR(H.DAILY_FEE * H.DURATION * (1 - 0.01 * CAST(REPLACE(D.DISCOUNT_RATE, '%', '') AS SIGNED)))
            ELSE DAILY_FEE * DURATION
        END AS FEE
    FROM TRUCK_HISTORY_INFO H
    JOIN TRUCK_DISCOUNT_INFO D
    ORDER BY HISTORY_ID DESC
)

SELECT HISTORY_ID, MIN(FEE) AS FEE
FROM TRUCK_POSSIBLE_FEES
GROUP BY HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC;