-- 코드를 입력하세요


# SELECT APNT_NO, 환자이름(PT_NO로 가져오기), PT_NO, MCDP_CD, 의사이름(의사ID로 가져오기), APNT_YMD
# FROM APPOINTMENT
# WHERE APNT_YMD = 2022-04-13 AND APNT_CNCL_YN IS NULL AND MCDP_CD = 'CS'
# ORDER BY APNT_YMD ASC;

WITH CS_INFO AS (
    SELECT APNT_NO, PT_NO, MCDP_CD, MDDR_ID, APNT_YMD
    FROM APPOINTMENT
    WHERE 
        YEAR(APNT_YMD) = 2022 AND
        MONTH(APNT_YMD) = 4 AND
        DAY(APNT_YMD) = 13 AND
        APNT_CNCL_YN = 'N' AND
        MCDP_CD = 'CS'
),
PATIENT_CS_INFO AS (
    SELECT C.APNT_NO, P.PT_NAME, C.PT_NO, C.MCDP_CD, C.MDDR_ID, C.APNT_YMD
    FROM CS_INFO C
    JOIN PATIENT P
    ON C.PT_NO = P.PT_NO
)



SELECT P.APNT_NO, P.PT_NAME, P.PT_NO, P.MCDP_CD, D.DR_NAME, P.APNT_YMD
FROM PATIENT_CS_INFO P
JOIN DOCTOR D
ON P.MDDR_ID = D.DR_ID
ORDER BY APNT_YMD ASC;







