-- 코드를 입력하세요
# 의사 이름, 의사 ID, 면허번호, 고용일자, 진료과코드, 전화번호
# DR_NAME, DR_ID, LCNS_NO, HIRE_YMB, MCDP_CD, TLNO

# WHERE MCDP_CD가 CS or GS
# SELECT DR_NAME, DR_ID, MCDP_CD, HIRE_YMD
# ORDER BY HIRE_YMB DESC, DR_NAME ASC;
SELECT DR_NAME, DR_ID, MCDP_CD, HIRE_YMD
FROM DOCTOR
WHERE MCDP_CD = 'CS'
   OR MCDP_CD = 'GS'
ORDER BY HIRE_YMD DESC, DR_NAME ASC;