-- 코드를 입력하세요

WITH REVIEW_COUNT_INFO AS (
    SELECT P.MEMBER_ID, P.MEMBER_NAME, COUNT(R.REVIEW_ID) AS REVIEW_COUNT
    FROM MEMBER_PROFILE P
    JOIN REST_REVIEW R
    ON P.MEMBER_ID = R.MEMBER_ID
    GROUP BY P.MEMBER_ID, P.MEMBER_NAME
),
MAX_REVIEW_COUNT_INFO AS (
    SELECT MAX(REVIEW_COUNT) AS MAX_REVIEW_COUNT
    FROM REVIEW_COUNT_INFO
)




SELECT P.MEMBER_NAME, R.REVIEW_TEXT, R.REVIEW_DATE
FROM REVIEW_COUNT_INFO P
JOIN REST_REVIEW R
ON P.MEMBER_ID = R.MEMBER_ID
WHERE EXISTS(
    SELECT 1
    FROM MAX_REVIEW_COUNT_INFO
    WHERE MAX_REVIEW_COUNT_INFO.MAX_REVIEW_COUNT = P.REVIEW_COUNT
)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;





# member_profile join rest_review 
# on member_profile.member_id = rest_review.member_id


# 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회

# 회원 이름, 리뷰 텍스트, 리뷰 작성일이 출력되도록 작성
# 리뷰 작성일 asc, 리뷰 텍스트 asc