-- 코드를 입력하세요

# PRODUCT_CODE 앞 두자리 별 상품 개수 출력
# CATEOGRY, PRODUCTS


SELECT SUBSTRING(PRODUCT_CODE, 1, 2) AS CATEGORY, COUNT(PRODUCT_ID) AS PRODUCTS
FROM PRODUCT
GROUP BY SUBSTRING(PRODUCT_CODE, 1, 2)
ORDER BY CATEGORY ASC;


