-- 코드를 작성해주세요

# 분화된 연도, 분화된 연도별 대장균 크기의 편차, 대장균 개체의 ID

# 1. 연도별로 가장 큰 대장균의 크기를 구하기 => 연도, 가장 큰 대장균의 크기
# 2. 분화된 연도: SUBSTRING을 통해 파싱 / 분화된 연도별 대장균 크기의 편차 / 대장균 개체의 ID



WITH MAX_SIZE_DATA AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE_OF_COLONY
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)


SELECT MAX_SIZE_DATA.YEAR, MAX_SIZE_DATA.MAX_SIZE_OF_COLONY - ECOLI_DATA.SIZE_OF_COLONY AS YEAR_DEV, ECOLI_DATA.ID
FROM ECOLI_DATA
JOIN MAX_SIZE_DATA
ON YEAR(DIFFERENTIATION_DATE) = MAX_SIZE_DATA.YEAR
ORDER BY MAX_SIZE_DATA.YEAR ASC, YEAR_DEV ASC;







