-- 코드를 작성해주세요

# 물고기 종류 별로 가장 큰 물고기의 ID, 이름, 길이
# 막힌 곳: 각 타입별로 가장 크기가 큰 것을 어떻게 찾지?

# SELECT INFO.ID, NAME.FISH_NAME, INFO.LENGTH
# FROM FISH_INFO INFO
# JOIN FISH_NAME_INFO NAME
# ON INFO.FISH_TYPE = NAME.FISH_TYPE
# WHERE INFO.LENGTH IS NOT NULL AND INFO.LENGTH

WITH MAX_TABLE AS (
    SELECT INFO.FISH_TYPE, NAME.FISH_NAME, MAX(INFO.LENGTH) AS MAX_LENGTH
    FROM FISH_INFO INFO
    JOIN FISH_NAME_INFO NAME
    ON INFO.FISH_TYPE = NAME.FISH_TYPE
    GROUP BY NAME.FISH_NAME
)

SELECT FISH_INFO.ID, MAX_TABLE.FISH_NAME, FISH_INFO.LENGTH
FROM FISH_INFO
JOIN MAX_TABLE
ON MAX_TABLE.FISH_TYPE = FISH_INFO.FISH_TYPE AND MAX_TABLE.MAX_LENGTH = FISH_INFO.LENGTH
ORDER BY FISH_INFO.ID ASC







# group by에다가 max를 하면, group by로 묶인 group에 대해서만
# max가 계산된다. row 전체가 아니라.

