-- 코드를 입력하세요
# BOOK_SALES: 각 도서의 날짜별 판매량
# 2022년 1월의 카테고리별 별 도서 판매량 합산
# => 카테고리, 총 판매량

# 1. JOIN을 통해 각 책 별 판매량 매핑하기
# 1. GROUP BY을 통해 각 책 별 판매량 구하기
# 2. GROUP BY를 통해 각 카테고리별 판매량 구하기


WITH SALES_BY_BOOK AS (
    SELECT BOOK.BOOK_ID, SUM(BOOK_SALES.SALES) AS SALES
    FROM BOOK
    JOIN BOOK_SALES
    ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
    WHERE BOOK_SALES.SALES_DATE LIKE '2022-01-__'
    GROUP BY BOOK.BOOK_ID
)

SELECT BOOK.CATEGORY, SUM(SALES_BY_BOOK.SALES) AS TOTAL_SALES
FROM BOOK
JOIN SALES_BY_BOOK
ON BOOK.BOOK_ID = SALES_BY_BOOK.BOOK_ID
GROUP BY BOOK.CATEGORY
ORDER BY BOOK.CATEGORY ASC;



