# 식품 분류별로 가격이 제일 비싼 식품
# 분류 / 가격 / 이름
# 식품 분류가 '과자', '국', '김치', '식용유' 인 경우만 출력
# 결과는 내림차순

SELECT FOOD_PRODUCT.CATEGORY, FOOD_PRODUCT.PRICE, FOOD_PRODUCT.PRODUCT_NAME
FROM FOOD_PRODUCT
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
) FOOD_PRICE
ON FOOD_PRODUCT.CATEGORY = FOOD_PRICE.CATEGORY AND FOOD_PRODUCT.PRICE = FOOD_PRICE.MAX_PRICE
WHERE FOOD_PRODUCT.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY PRICE DESC;

# group 별로 가장 큰 값을 가진 ROW 전체를 가져오는 방법
# 서브쿼리 + JOIN